### PR TITLE
Support immutable.js

### PR DESCRIPTION
**Pull request by VladimirPal**
It's very sad but when you use immutable.js with redux-form it sends immutable data to validate function and revalidate doesn't work. I've created patch for support immutable.js with toJS function for creating JS object, i know it's not very good solution, but it's better then nothing.

### CODE REVIEW

**Comment by jfairbank** [comment]
Hi, @VladimirPal! Thanks for the PR.

Even though Immutable.js is a wonderful library, I'm hesitant to tightly couple revalidate to it. Instead, I would prefer a more general approach that allows you to serialize form data in a manner similar to the `getFormState` option of Redux Form (https://github.com/erikras/redux-form/blob/master/docs/faq/ImmutableJs.md).

Therefore, if `combineValidators` supported a new optional `options` parameter that contained something like a `serializeValues` function option, I would definitely accept that PR. If `serializeValues` isn't supplied by the user, then it can default to the identity function.

```js
const options = {
  serializeValues: values => values.toJS(),
};

const myValidator = combineValidators({
  foo: isRequired('Foo'),
  bar: isAlphaNumeric('Bar'),
}, options);
```

**Comment by jfairbank** [comment]
Hi, @VladimirPal! Just checking in. Are you still interested in tweaking this PR per my earlier request? Thanks!

**Comment by VladimirPal** [comment]
@jfairbank I think there is no need in this PR.

**Comment by jfairbank** [comment]
I recognize that it would be nice for revalidate to work with Immutable.js, but this solution is too tightly coupled. I don't want to tie down a second parameter specifically to Immutable.js. If there is ever a need for future options to `combineValidators`, then I'll have to add additional parameters or make a breaking change to change the second parameter to an option object. I would strongly prefer a more general approach like the one I suggested. That way one could use whatever state representation, whether it's Immutable.js, a plain object, or something else.

I really appreciate your work and taking the time to highlight the need for this in revalidate, but I'm going to close this PR because I can't accept it as is. I think the general approach I suggested is worth adding, so I may do it in the near future. However, if you're interested in doing it, you're more than welcome to.

**Pull request closed without merging**
